### ISSUE TITLE
Create the Like relation table

### ISSUE THREAD

**Issue by MrAnyx** [MrAnyx/Notice#12]
## Suggested solution

This table will be used to retrieve like for each user

## Todo
- [x] Use the symfony command `php bin/console make:entity` and update the `Thread` entity
- [x] Add the following fields
   - `likedBy` of type `relation` with `User`
- [x] Run the command `php bin/console make:migration`
- [x] Run the command `php bin/console d:m:m` or `php bin/console doctrine:migrations:migrate`
- [x] Update the `AppFixtures` and `TestFixtures`
