### ISSUE TITLE
Create the registration system

### ISSUE THREAD

**Issue by MrAnyx** [MrAnyx/Notice#19]
## Suggested solution

Currently, the login system is working but users can not create their account. We'll create a custom registration, system with a custom form design

## Linked issue

#10 

## Todo
- [x] Use the command `php bin/console make:registration-form` as an example
- [x] Create the registration controller
- [x] Create the Twig view to show the form
- [x] Handle errors (duplications, constraints validation)
- [x] Add the automatic login after registration
- [x] Send verification email with an expiration date with the same method as the registration-form command
- [x] Create the email verification email
