### ISSUE TITLE
Create the follow relation entity

### ISSUE THREAD

**Issue by MrAnyx** [MrAnyx/Notice#20]
## Suggested solution

The feed will be based on the following of a user.

## Todo
- [ ] Update the `User` entity
- [ ] create 2 new fields to represent the followers and the followings
- [ ] Update the fixtures (App and Test)
- [ ] Update the tests
