### ISSUE TITLE
Design the auth pages

### ISSUE THREAD

**Issue by MrAnyx** [MrAnyx/Notice#21]
## Suggested solution

Login and registration pages are working but are very ugly.

## Template

https://dribbble.com/shots/14981045-Login-Sign-in
https://dribbble.com/shots/17564792-Log-in-page-Untitled-UI

## Todo
- [x] Follow the template to design the auth pages
- [x] Create another layout for authentication pages
- [ ] Design error messages
