### ISSUE TITLE
Implement the "forgot password" feature

### ISSUE THREAD

**Issue by MrAnyx** [MrAnyx/Notice#23]
## Suggested solution

To create a fully functional login form, we need to implement the forgot password feature. It will send an email to the user with a reset link

## Todo
- [x] Create the route to allow the user to specify his email
- [x] Send to email with an expiration date (like the verif email)
- [x] Create the route to change the password
- [x] Update the user's password
