### ISSUE TITLE
Implement Laravel Pint

### ISSUE THREAD

**Issue by MrAnyx** [MrAnyx/Notice#28]
## Suggested solution

Currently, the project uses php_codesniffer, but recently, Laravel release a new tool called Pint that help developers format their code. And they also release a vscode extension to format the code automatically

## Todo
- [ ] Install the composer package
- [ ] Install the vscode package https://marketplace.visualstudio.com/items?itemName=open-southeners.laravel-pint
- [ ] Update github action
- [ ] Update composer scripts
