### ISSUE TITLE
Update the component scss file import location

### ISSUE THREAD

**Issue by MrAnyx** [MrAnyx/Notice#29]
## Suggested solution

Currently, the scss files are imported directly in the js global file. We need to import it in each component.ts file

## Todo
- [ ] Update scss file import location for lit components
- [ ] Update typescript files
- [ ] Update `encore_entry_link_tags` function in each twig files
