### ISSUE TITLE
Create the trending hashtags section

### ISSUE THREAD

**Issue by MrAnyx** [MrAnyx/Notice#5]
## Suggested solution

Create the sidebar that will contain the trending hashtags

## Template

https://www.figma.com/file/NL0mfmUyu8dfkkVHdIfJah/Projet-Hydrogen?node-id=172%3A657

## Todo
- [x] Create this section in the `layout.html.twig` file
- [x] Reproduce the design from the mockup
- [x] Create the dropdown to select the trending period of time
- [x] For now, only create the layout, don't create the request to retrieve hashtags
