### ISSUE TITLE
Create the Thread entity

### ISSUE THREAD

**Issue by MrAnyx** [MrAnyx/Notice#8]
## Suggested solution

Because this project is a thread based project, we'll need to create the `Thread` entity to represent a message and replies

## Linked issue

Create the User entity [#9](https://github.com/MrAnyx/Notice/issues/9)

## Todo
- [x] Use the command `php bin/console make:entity` and call it `Thread`
- [x] Add the following fields
   - `id` as a `Uuid`
   - `createdAt` as a `Datetime`
   - `content` as a `Text`
   - `threadId` as a `Uuid`
   - `parentThreadId` as a `Uuid`
   - `author` as a relation with the entity `User`
- [x] Create the migration with `php bin/console make:migration`
- [x] Execute the migration to update the database `php bin/console d:m:m` or `php bin/console doctrine:migrations:migrate`
