### ISSUE TITLE
Create the User entity

### ISSUE THREAD

**Issue by MrAnyx** [MrAnyx/Notice#9]
## Suggested solution

This entity will be used to create account, login, and it will be linked to the `Thread` entity

## Linked issue

Create the Thread entity [#8](https://github.com/MrAnyx/Notice/issues/8)

## Todo
- [x] Use the symfony command `php bin/console make:user` to create the user entity
- [x] Use the email as the identifier
- [x] add the following fields
   - `username` as a `string`
   - `createdAt` as a `Datetime`
